version: '3'
services:
  web:
    container_name: news-scraping-api
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/scraper
    depends_on:
      - db
  db:
    container_name: news-scraping-db
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=scraper
    ports:
      - "5432:5432"