server:
  port: 8181
website:
  urls: https://mashable.com/tech,https://gizmodo.com/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scraper

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  jpa:
    hibernate:
      ddl-auto: update

spring:
  datasource:
    username: postgres

spring:
  datasource:
    password: admin