server:
  port: 8888

website:
  urls: https://mashable.com/tech,https://gizmodo.com/tech/news

spring:
  datasource:
    url: jdbc:postgresql://scraper.cgo2b0cgqeqa.us-east-1.rds.amazonaws.com/scraper?useSSL=false
    username: postgres
    password: testdabase312
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update