name: CI/CD Pipeline
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
jobs:
  #Maven Build Job
  mvn_build:
    name: Build
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Run mvn clean install and Bump Version
      - name: Run Maven Install amd Bump Version
        run: mvn clean install -DbumpMinor -Dmaven.test.skip

  #Test's job
  tests:
    #Depends on test's job
    needs: mvn_build
    name: Unit Testing
    #Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    #Job's steps
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      #Run Tests - mutation coverage (Threshold 80%)
      - name: Run Unit Tests
        run: mvn -B test

  #Test's job
  performance-test:
#    needs: tests
    name: Performance Testing
    runs-on: ubuntu-latest
    steps:
      #Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v1
      #Set up JDK 11
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      #Set up Maven cache
      - name: Cache Maven packages
        #This action allows caching dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Clean package
        run: mvn clean package
      - name: Run Performance Testing for NewsController
        run: mvn gatling:test -Dgatling.simulationClass=net.dg.newsscrapingapi.performance.NewsControllerPerformanceTesting
      - name: Publish NewsController Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: target/gatling/newscontroller
      - name: Sleep for 10 seconds
        run: sleep 10s
      - name: Run Performance Testing for ScrapeController
        run: mvn gatling:test -Dgatling.simulationClass=net.dg.newsscrapingapi.performance.ScrapeControllerPerformanceTesting
      - name: Publish ScrapeController Reports to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: target/gatling/scrapecontroller

  owasp:
    permissions: write-all
    name: OWASP ZAP SCANS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Building Docker Image
        run: docker-compose build
      - name: Launching the app
        run: docker-compose up --detach

      - name: OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:5000'
          issue_title: OWASP Security Testing


